config/routes.rb
PedalPushr::Application.routes.draw do
  get "users/show"

  resources :pedals

  devise_for :users
  match 'users/:id' => 'users#show', as: :user

  get 'about' => 'pages#about'

  root :to => 'pedals#index'

end

app/models/pedal.rb
class Pedal < ActiveRecord::Base
  attr_accessible :price, :rating, :title, :image, :image_remote_url


# check out Rails validations for length, presence, etc.
  validates :title, presence: :true, length: { maximum: 100}
  validates :user_id, presence: true
  validates_attachment :image, presence: true, 
  														 content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
  														 size: { less_than: 5.megabytes }

  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240>"}

  def image_remote_url=(url_value)
  	self.image = URI.parse(url_value) unless url_value.blank?
  	super
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable #:recoverable,

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  #look up these type of associations by searching for Rails associations
  has_many :pedals

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/controllers/pedals_controller.rb
class PedalsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /pedals
  # GET /pedals.json
  def index
    @pedals = Pedal.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pedals }
      format.js
    end
  end

  # GET /pedals/1
  # GET /pedals/1.json
  def show
    @pedal = Pedal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pedal }
    end
  end

  # GET /pedals/new
  # GET /pedals/new.json
  def new
    # this assigns new pedals to the current user
    @pedal = current_user.pedals.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pedal }
    end
  end

  # GET /pedals/1/edit
  def edit
    @pedal = current_user.pedals.find(params[:id])
  end

  # POST /pedals
  # POST /pedals.json
  def create
    # this assigns the pedal to the current user
    @pedal = current_user.pedals.new(params[:pedal])

    respond_to do |format|
      if @pedal.save
        format.html { redirect_to @pedal, notice: 'Pedal was successfully created.' }
        format.json { render json: @pedal, status: :created, location: @pedal }
      else
        format.html { render action: "new" }
        format.json { render json: @pedal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pedals/1
  # PUT /pedals/1.json
  def update
    @pedal = current_user.pedals.find(params[:id])

    respond_to do |format|
      if @pedal.update_attributes(params[:pedal])
        format.html { redirect_to @pedal, notice: 'Pedal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pedal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedals/1
  # DELETE /pedals/1.json
  def destroy
    @pedal = current_user.pedals.find(params[:id])
    @pedal.destroy

    respond_to do |format|
      format.html { redirect_to pedals_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@pedals = @user.pedals.page(params[:page]).per_page(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pedals_helper.rb
module PedalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
   <form class="navbar-search pull-left">
		<input type="text" class="search-query" placeholder="Search">
			</form>
    <div class="container">
     
    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </a>

    <!-- Be sure to leave the brand out there if you want it shown -->
    <%= link_to "PedalPushr", root_path, class: "brand" %>
    <!-- Everything you want hidden at 940px or less, place within here -->
	  
	    <div class="nav-collapse collapse">
	    	<ul class="nav">
					<li><%= link_to "About", about_path %></li>
				</ul>
				<ul class="nav pull-right">
					<% if user_signed_in? %>
						<li><%= link_to "List a Pedal", new_pedal_path %></li>
						<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
						<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
					<% else %>	
						<li><%= link_to "Login", new_user_session_path %></li>
						<li><%= link_to "Sign up now", new_user_registration_path %></li>
					<% end %>

					
				</ul>
    <!-- .nav, .navbar-search, .navbar-form, etc -->
			</div> 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>PedalPushr</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
      <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>
			<%= yield %>
			<br>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/_home.html.erb
<% unless user_signed_in? %>
	<div class="hero-unit">
		<div class="row">
		  <div class="span2"><h2>Filter</h2></div>
		  <div class="span8"><h1>Welcome to PedalPushr!  \m/</h1>
				<p>Like Etsy for your guitar feet tools.
					<%= link_to "PedalPushr", "http://PedalPushr.com" %>
				</p>
				<br><%= link_to "Sign up now", new_user_registration_path, class: "btn btn-primary btn-large" %></br>
			</div>
		</div>
	</div>
<% end %>

app/views/pages/about.html.erb
<h1>About</h1>


<p>
	<%= link_to "PedalPushr", "http://PedalPushr.com" %> is a way to discover and buy new guitar pedals!
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<h1>PUT A SWEET APP HERE</h1>
<% else %>
	<div class="hero-unit">
		<div class="row">
		  <div class="span2"><h2>Filter</h2></div>
		  <div class="span8"><h1>Welcome to PedalPushr!  \m/</h1>
				<p>Like Etsy for your guitar feet tools.
					<%= link_to "PedalPushr", "http://PedalPushr.com" %>
				</p>
				<br><%= link_to "Sign up now", new_user_registration_path, class: "btn btn-primary btn-large" %></br>
			</div>
		</div>
	</div>
<% end %>

app/views/pedals/_form.html.erb
<%= simple_form_for(@pedal, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  	<%= f.input :image, label: "Upload an image" %> 
    <%= f.input :image_remote_url, label: "or enter a URL" %>
    <%= f.input :title, as: :text, input_html: { rows: "1" } %>
    <%= f.input :rating %>
    <!--Review the money-rails gem by RubyMoney to make price format, change currency, etc.-->
    <%= f.input :price %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pedals/_pedal.html.erb
<div class="box">
	<%= link_to (image_tag pedal.image(:medium)), pedal %>
	<p>
			<%= pedal.title %>
	</p>
		<p style="text-align:left;">
			&nbsp;&nbsp;&nbsp;<%= pedal.rating %>
			<span style="float:right;"><%= pedal.price %>&nbsp;&nbsp;&nbsp;
		</p>
	</p>
	<div style="text-align:right">
			Made by <%= link_to pedal.user.name, pedal.user %>
	</div>
	<% if current_user == pedal.user %>
		<p>
			<%= link_to 'Edit', edit_pedal_path(pedal) %>
			<%= link_to 'Destroy', pedal, method: :delete, data: { confirm: 'Are you sure?' } %>
		</p>
	<% end %>
</div>

app/views/pedals/edit.html.erb
<h1>Editing pedal</h1>

<%= render 'form' %>

<%= link_to 'Show', @pedal %> |
<%= link_to 'Back', pedals_path %>

app/views/pedals/index.html.erb
<%= render 'pages/home' %>

<div id="pedals">
  <%= render @pedals %>
</div>

<%= will_paginate @pedals %>

app/views/pedals/index.js.erb
$boxes = $('<%= j render(@pedals) %>')

$('#pedals').append( $boxes ).imagesLoaded( function(){
    $('#pedals').masonry( 'reload');
});
<% if @pedals.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate(@pedals) %>');
<% else %>
    $('.pagination').remove();
<% end %>

app/views/pedals/new.html.erb
<h1>New pedal</h1>

<%= render 'form' %>

<%= link_to 'Back', pedals_path %>

app/views/pedals/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @pedal.image %>
			<p>
			  <%= @pedal.title %>
			</p>
			<p>
			  <%= @pedal.rating %>
			</p>
			<p>
			  <%= @pedal.price %>
			</p>
				<p>
			  <%= @pedal.user.name %>
			</p>
			<% if current_user == @pedal.user %>
				<%= link_to 'Edit', edit_pedal_path(@pedal) %> |
			<% end %>
			<%= link_to 'Back', pedals_path %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<div id="pedals">
  <%= render @pedals %>
</div>

<%= will_paginate @pedals %>